const weekImages: { [key: number]: any } = {
    //   1: require('../assets/weeks/images/week1.jpg'),
    //   2: require('../assets/weeks/images/week2.jpg'),
    //   3: require('../assets/weeks/images/week3.jpg'),
    4: require('../assets/weeks/images/week4.jpg'),
    5: require('../assets/weeks/images/week5.jpg'),
    6: require('../assets/weeks/images/week6.jpg'),
    7: require('../assets/weeks/images/week7.jpg'),
    8: require('../assets/weeks/images/week8.jpg'),
    9: require('../assets/weeks/images/week9.jpg'),
    10: require('../assets/weeks/images/week10.jpg'),
    11: require('../assets/weeks/images/week11.jpg'),
    12: require('../assets/weeks/images/week12.jpg'),
    13: require('../assets/weeks/images/week13.jpg'),
    14: require('../assets/weeks/images/week14.jpg'),
    15: require('../assets/weeks/images/week15.jpg'),
    16: require('../assets/weeks/images/week16.jpg'),
    17: require('../assets/weeks/images/week17.jpg'),
    18: require('../assets/weeks/images/week18.jpg'),
    19: require('../assets/weeks/images/week19.jpg'),
    20: require('../assets/weeks/images/week20.jpg'),
    21: require('../assets/weeks/images/week21.jpg'),
    22: require('../assets/weeks/images/week22.jpg'),
    23: require('../assets/weeks/images/week23.jpg'),
    24: require('../assets/weeks/images/week24.jpg'),
    25: require('../assets/weeks/images/week25.jpg'),
    26: require('../assets/weeks/images/week26.jpg'),
    27: require('../assets/weeks/images/week27.jpg'),
    28: require('../assets/weeks/images/week28.jpg'),
    29: require('../assets/weeks/images/week29.jpg'),
    30: require('../assets/weeks/images/week30.jpg'),
    31: require('../assets/weeks/images/week31.jpg'),
    32: require('../assets/weeks/images/week32.jpg'),
    33: require('../assets/weeks/images/week33.jpg'),
    34: require('../assets/weeks/images/week34.jpg'),
    35: require('../assets/weeks/images/week35.jpg'),
    36: require('../assets/weeks/images/week36.jpg'),
    37: require('../assets/weeks/images/week37.jpg'),
    38: require('../assets/weeks/images/week38.jpg'),
    39: require('../assets/weeks/images/week39.jpg'),
    40: require('../assets/weeks/images/week40.jpg'),
};

export default weekImages;